### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by justinmc** [dlmanning/browserify-handlebars#6]
Does browserify-handlebars support partials?  I tried using `Handlebars.registerPartial('myPartial', myPartialTemplate())`, but I got the error `The partial myPartial could not be compiled when running in runtime-only mode`.

I'm requiring handlebars like this `require('handlebars/runtime').default` as noted in issue https://github.com/dlmanning/browserify-handlebars/issues/1.

**Comment by ndesorden** [comment]
Maybe a little late, but:

```
var handlebars = require('handlebars/runtime').default;
var template = require('../views/template.handlebars');
var templatePartial = require('../views/template-partial.handlebars');
handlebars.registerPartial('myPartial', templatePartial);
var html = template(...);
```
